apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/part-of: payment-system
      app.kubernetes.io/support-by: team_1
  template:
    metadata:
      labels:
        app: my-app
        app.kubernetes.io/part-of: payment-system
        app.kubernetes.io/support-by: team_1
    spec:
      containers:
        - name: my-container
          image: nginx:latest
